[tool.poetry]
name = "github-workflow-tool"
version = "0.1.0"
description = "A CLI tool to manage GitHub Actions workflow runs in a repository."
authors = ["Sebastian Blum <sebast.blum@gmail.com>"]
license = "MIT"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
requests = "^2.28.1"

[tool.poetry.scripts]
github-workflow = "src.main:manage_workflow_runs"
